# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('level', models.IntegerField(choices=[(0, 'Project'), (1, 'Sprint'), (2, 'User Story')], verbose_name='Level')),
                ('type', models.IntegerField(choices=[(0, 'File'), (1, 'Source')], verbose_name='Type')),
                ('trace_code', models.CharField(max_length=100, verbose_name='Trace Code')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('requester', models.CharField(max_length=100, verbose_name='Requester')),
                ('description', models.TextField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('status', models.IntegerField(choices=[(0, 'Planning'), (1, 'Executing'), (2, 'Close')], verbose_name='Status')),
                ('begin', models.DateField(verbose_name='Begin')),
                ('end', models.DateField(verbose_name='End')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='SprintUserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Story not Completed'), (1, 'Complete story')], default=0, verbose_name='Status')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sprint', verbose_name='Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Taks')),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Estimated Time (Hours)')),
                ('realizated_time', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Realizated Time (Hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='userstory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserStory', verbose_name='UserStory'),
        ),
        migrations.AddField(
            model_name='sprintuserstory',
            name='userstory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserStory', verbose_name='User Story'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ArtifactType', verbose_name='Artifact type'),
        ),
    ]
