# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_project_repository_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.URLField(default=1, verbose_name='Repository URL'),
            preserve_default=False,
        ),
    ]
